exercise1
blank-4/exercises-harouna-kanoute pull request #14
Opened 2018-11-26 15:51 UTC by harouna-kanoute

2018-11-26 15:53 UTC, Neilsafraoui requested changes
il manque le else dans ce que je vois

2018-11-26 15:53 UTC, Neilsafraoui commented on javascript/lesson2/exercise1/execise/main.js
> +
et le "else"?
l'énoncé dit : "et sinon, on affiche "c'est le soir" dans la console."

2018-11-26 16:38 UTC, Neilsafraoui approved these changes
je valide, mais attention au signes strictement > ou <, parfois on doit utiliser >= ou <= (supérieur ou égal, et inférieur ou égal)

2018-11-26 16:38 UTC, Neilsafraoui commented on javascript/lesson2/exercise2/exercise/main.js
> +for ( var i = 0 ; i < 100 ; i++ ) {
détail : on veut aller jusqu'à 100, ici ça s'arrête à 99, donc il faut utiliser "<=" (inférieur ou égal)

2018-11-26 16:38 UTC, Neilsafraoui commented on javascript/lesson2/exercise2/exercise/main.js
> +for ( var i = 0 ; i < 100 ; i = i + 2) {
idem que précédemment

2018-11-26 16:38 UTC, Neilsafraoui commented on javascript/lesson2/exercise2/exercise/main.js
> +for ( var i = 100 ; i > 0 ; i = i - 2) {
idem, ici, >= (supérieur ou égal)

2018-11-26 16:50 UTC, FaXaq commented on javascript/lesson2/exercise3/exercise/main.js
> +while (n < 100) {
nickel ! Tu peux simplifier le code en mettant `while (var n < 100)`

2018-12-10 09:28 UTC, FaXaq commented
Je merge, n'hésite pas à regarder la correction

2018-12-10 09:28 UTC, merged